site_name: Fisseq Data Pipeline
nav:
  - Home: index.md
  - Architecture: architecture.md
  - Installation: installation.md
  - Nextflow Workflow: nextflow.md
  - CLI Reference:
      - QC Filter: cli/qcfilter.md
      - Normalize: cli/normalize.md
      - Aggregate: cli/aggregate.md
      - Feature Selection: cli/features.md
      - Batch Correction: cli/batchcorrect.md
      - PERMANOVA: cli/permanova.md
      - One-vs-WT: cli/ovwt.md
      - OvWT Cell Scores: cli/ovwtcellscores.md
      - Batch vs. Batch: cli/batchvsbatch.md
  - API Reference:
      - qcfilter: api/qcfilter.md
      - normalize: api/normalize.md
      - aggregate: api/aggregate.md
      - features: api/features.md
      - batchcorrect: api/batchcorrect.md
      - permanova: api/permanova.md
      - ovwt: api/ovwt.md
      - ovwtcellscores: api/ovwtcellscores.md
      - batchvsbatch: api/batchvsbatch.md
      - config: api/config.md
      - utils: api/utils.md
  - Walkthrough: walkthrough.md
theme:
  name: readthedocs
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: numpy
            show_root_heading: true
            show_signature: true
            separate_signature: false
            show_source: true
            heading_level: 3
